name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: "https://rkss.jfrog.io/artifactory/uii-docker-docker-local/"
  IMAGE_NAME: myimage

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Generate short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Login to JFrog Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.JFROG_REGISTRY_USERNAME }}
          password: ${{ secrets.JFROG_REGISTRY_PASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}
            ${{ env.IMAGE_NAME }}:latest
